contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #seia channel"
    url: https://nfcore.slack.com/channels/seia
    about: Discussion about the nf-core/seia pipeline
