contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #enhancerflow channel"
    url: https://nfcore.slack.com/channels/enhancerflow
    about: Discussion about the nf-core/enhancerflow pipeline
